#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage() {
	echo "usage: add-user [ -s ] [ -n REAT_NUMBER ] NAME USER [PASSWORD ]"
}

# check options
FLG_N=0; RNUM=0
FLG_S=0; SFLG=""

while getopts n:s OPT
do
  case $OPT in
    "n" ) FLG_N=1; RNUM=$OPTARG ;;
    "s" ) FLG_S=1; SFLG="-s" ;;
    \?  ) usage; exit -1 ;;
  esac
done

shift `expr $OPTIND - 1`

if [ $# -ne 2 -a $# -ne 3 ]; then
	usage
	exit -1
fi

NAME=$1
UNAME=$2
PASSWORD=""
if [ $# -eq 3 ]; then
	PASSWORD=$3
fi

if [ $FLG_N -gt 0 ]; then
	for i in `seq $RNUM`
	do
		NAME_N=`printf "%s%04d" $NAME $i`
		add-user $SFLG $NAME_N $UNAME $PASSWORD
	done
else
	add-user $SFLG $NAME $UNAME $PASSWORD
fi

exit 0


