#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage()
{
	echo "usage: br-del BRIDGE_NUMBER ( IPADDR/MASK | NET_DEVICE )"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

BRNO=$1
net-ipv4 $2 >& /dev/null
if [ $? -eq 0 ]; then
	NETDEV=""
	IPMASK=$2
else
	NETDEV=$2
	ip a show $NETDEV >& /dev/null
	if [ $? -ne 0 ]; then
		echo "error:" $NETDEV "does not exist"
		exit -1
	fi
	IPMASK=`ip a show fulcon$BRNO | awk 'NR==3{print $2}'`

	FLG=0
	for i in `brctl show fulcon$BRNO | awk 'NR>1{print $NF}'`
	do
		if [ x"$i" == x"$NETDEV" ]; then
			FLG=1
		fi
	done
	if [ $FLG -eq 0 ]; then
		echo "error: Device is not target:" $NETDEV
		exit -1
	fi

	ip addr add $IPMASK dev $NETDEV
fi

# delete all interface
for i in `brctl show fulcon$BRNO | awk 'NR>1{print $NF}'`
do
	brctl delif fulcon$BRNO $i
done

# delete bridge
ip link set fulcon$BRNO down
brctl delbr fulcon$BRNO


