#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage()
{
	echo "usage: br-info"
}

if [ $# -ne 1 -o x"$1" != x"br-info" ]; then
	usage
	exit -1
fi

. br-info $@

exit 0
