#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage()
{
	echo "usage: clone CONTAINER_NAME NEW_IMAGENAME"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

. clone $@

exit 0


