#!/bin/sh

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`driver-name`
PATH=/usr/lib64/fulcon/driver/$FULCONDRIVER:$PATH


# check options
FLG_X=0
FLG_N=0
RNUM=0

while getopts xn: OPT
do
  case $OPT in
    "x" ) FLG_X=1 ; FLG_I=1;;
    "n" ) FLG_N=1 ; RNUM=$OPTARG ;;
  esac
done

shift `expr $OPTIND - 1`

usage() {
	echo "usage: console [ -x ] [ -n REPEAT_NUMBER] NAME"
}

if [ $FLG_N -eq 1 ]; then
	if [ $# -ne 1 ]; then
		usage
		exit -1
	fi
	NAME=$1
	if [ $RNUM -gt 0 -a $RNUM -lt 1000 ]; then
		for i in `seq $RNUM`
		do
			N=`printf "%04d" $i`
			gnome-terminal -e "console $NAME$N"
		done;
		exit 0
	else
		echo "REPEAT_NUMBER must be [1...999]"
		exit -1
	fi

fi

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

NAMES=$@

if [ x"$NAMES" == x"console" ]; then
	usage
	exit -1
fi

for i in $NAMES
do
	if [ $FLG_X -eq 0 ]; then
		console $i
	else
		gnome-terminal -e "console $i"
	fi
done

exit 0
