#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

umask 022

usage()
{
	echo "usage: default-image"
}

if [ $# -ne 1 -o x"$1" != x"default-image" ]; then
	usage
	exit -1
fi

if [ -f /var/lib/fulcon/default-image ]; then
	IMAGENAME=`cat /var/lib/fulcon/default-image`
else
	IMAGENAME=""
fi


if [ x"$IMAGENAME" == x"" ]; then
	for i in `fulcon ls-image | awk '(NR>1){print}'`
	do
		IMAGENAME=$i
		fulcon set-default-image $IMAGENAME >& /dev/null
		break
	done
fi

if [ x"$IMAGENAME" == x"" ]; then
	echo "error: can't find Image"
	exit -1 
fi

echo $IMAGENAME

exit 0
