#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage() {
	echo "usage: del-user NAME USER"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"del-user" ]; then
	usage
	exit -1
fi

. del-user $@

exit 0


