#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDIR=/var/lib/fulcon

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH
umask 022

usage() {
	echo "usage: image-catalog"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"image-catalog" ]; then
	usage
	exit -1
fi

. image-catalog $@
