#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: lib-resume NAME"
}

if [ $# -eq 1 ]; then
	NAME=$1
else
	usage
	exit -1
fi

STAT=`fulcon list | awk '($1=="'$NAME'"){print $2}'`
if [ x"$STAT" != x"PAUSED" ]; then
	echo "error: not PAUSED" 
	exit -1
fi

fulcon-resume $NAME

exit 0
