#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

ls /var/lib/fulcon/driver/dockerfile/* >& /dev/null
if [ $? -ne 0 ]; then 
	echo "error: there is not a image"
	exit -1
fi

usage() {
	echo "usage: lib-image-catalog"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

cd /var/lib/fulcon/driver/dockerfile

for i in *
do
	echo "fulcon/"$i
done

exit 0

