#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki


# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

usage()
{
	echo "usage: lib-del-user NAME USER"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

LXCNAME=$1
USERNAME=$2
fulcon-exec $LXCNAME userdel -r $USERNAME
if [ $? -ne 0 ]; then
	echo "error: del-user is failed"
	exit -1
fi

exit 0
