#!/bin/sh

# Copyright (C) 2015-2016 NIWA Hideyuki

usage() {
	echo "usage: lib-update NUMBER ..."
}

update_ubuntu() {
	if [ x"$STATUS" == x"RUNNING" ]; then
		echo "update" $NAME
		fulcon-exec $NAME apt-get update
		fulcon-exec $NAME apt-get upgrade -y
		echo 
		echo
	elif [ x"$STATUS" == x"STOPPED" ]; then
		echo "update" $NAME
		fulcon start $NAME
		fulcon-exec $NAME apt-get update
		fulcon-exec $NAME apt-get upgrade -y
		fulcon stop $NAME
		echo 
		echo
	fi
}

update_centos() {
	if [ x"$STATUS" == x"RUNNING" ]; then
		echo "update" $NAME
		fulcon-exec $NAME yum update -y
		echo 
		echo
	elif [ x"$STATUS" == x"STOPPED" ]; then
		echo "update" $NAME
		fulcon start $NAME
		fulcon-exec $NAME yum update -y
		fulcon stop $NAME
		echo 
		echo
	fi
}

if [ $# -lt 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"update" ]; then
	usage
	exit -1
fi

LISTNAME=$*

for i in `fulcon list $LISTNAME | awk '{printf "%s:%s:%s\n",$1,$2,$3}'`
do
	NAME=`echo $i | awk -F ":" '{print $1}'`
	STATUS=`echo $i | awk -F ":" '{print $2}'`
	IMAGE=`echo $i | awk -F ":" '{print $3}'`

	echo
	echo "########## $NAME $STATUS ##########"
	echo

	echo $IMAGE | grep 'ubuntu' >& /dev/null
	if [ $? -eq 0 ]; then
		update_ubuntu
	fi

	echo $IMAGE | grep 'centos' >& /dev/null
	if [ $? -eq 0 ]; then
		update_centos
	fi
		
	echo $IMAGE | grep 'slot-os' >& /dev/null
	if [ $? -eq 0 ]; then
		if [ -f /etc/redhat-release ]; then
			update_centos
		else
			update_ubuntu
		fi
	fi
done


exit 0
