#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

usage()
{
	echo "usage: lib-ls-image"
}

echo "fulcon images:"
IMAGES=`fulcon-ls-image | awk '($1~/fulcon\//){printf "\t%s\n",$1}'`

if [ x"$IMAGES" == x"" ]; then
	exit -1
else
	for i in $IMAGES
	do
		IMG=`echo $i | awk '{n=split($1,img,"/");if(n==3)printf "%s/%s",img[2],img[3]; else printf "%s/%s",img[1],img[2]}'`
		printf "\t%s\n" $IMG
	done
	exit 0
fi
