#!/bin/sh

# Copyright (C) 2015-2016 NIWA Hideyuki

# check options
FLG_E=0

usage() {
	echo "usage: lib-console NAME"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

NAME=$1

fulcon-exec $NAME /bin/bash

exit 0
