#!/bin/bash 

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDIR=/var/lib/fulcon

usage()
{
	echo "usage: lib-list [ NAME ]"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

driver-net-info()
{
	fulcon-exec $1 ip a show
}

RUNNING=`fulcon-list-running | awk '{printf "%s ",$1}'`
PAUSED=`fulcon-list-paused | awk '{printf "%s ",$1}'`
ALLCONT=`fulcon-list-all | awk '{printf "%s ",$1}'`

list1()
{
	NAME=$1
	mkdir -p $FULCONDIR/slot/$NAME/net
	if [ -f /var/lib/fulcon/container/$NAME/imagename ]; then
		IMAGE=`cat /var/lib/fulcon/container/$NAME/imagename`
		echo $RUNNING | egrep -w $NAME >& /dev/null
		if [ $? -eq 0 ]; then
			STATUS="RUNNING"

			# network information
			IPADDR=`driver-net-info $NAME | \
			  awk '$1=="inet" && $2!="127.0.0.1/8"{printf "%s ", $2}'`
			printf "%s\t\tRUNNING\t\t%s $IPADDR\n" $NAME $IMAGE
		else
			# network information
			IPADDR=""
			for k in `lsdir $FULCONDIR/container/$NAME/net`
			do
				IP1=`awk '{printf "%s ",$3}' $FULCONDIR/container/$NAME/net/$k`
				IPADDR="$IPADDR $IP1"
			done

			echo $PAUSED | egrep -w $NAME >& /dev/null
			if [ $? -eq 0 ]; then
				STATUS="PAUSED"
				printf "%s\t\tPAUSED\t\t%s$IPADDRs\n" $NAME $IMAGE
			else
				STATUS="STOPPED"
				printf "%s\t\tSTOPPED\t\t%s$IPADDR\n" $NAME $IMAGE
			fi
		fi
	fi
}

if [ $# -eq 1 ]; then
	list1 $1
else
	for i in $ALLCONT
	do
		list1 $i
	done | sort
fi

exit 0


