#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: lib-resume NAME"
}

if [ $# -eq 1 ]; then
	NAME=$1
else
	usage
	exit -1
fi

STAT=`fulcon status $NAME`
if [ x"$STAT" != x"SUSPENDED" ]; then
	echo "error: not SUSPENDED $NAME" 
	exit -1
fi

fulcon-resume $NAME >& /dev/null

exit 0
