#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: lib-rename NAME NEW_NAME"
}

if [ $# -eq 2 ]; then
	NAME=$1
	NEWNAME=$2
else
	usage
	exit -1
fi

echo $NAME "->" $NEWNAME
fulcon-rename $NAME $NEWNAME
mv $LIBDIR/container/$NAME $LIBDIR/container/$NEWNAME

exit 0
