#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: lib-setup-prog CONTAINER_NAME COMMAND"
}

if [ $# -lt 2 ]; then
	usage
	exit -1
fi

NAME=$1
shift

CMD=$*

echo '***' $NAME '***'
echo

fulcon-exec $NAME $CMD

echo
echo '****************'



