#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: lib-sysgen NAME IMAGE"
}

if [ $# -eq 2 ]; then
	NAME=$1
else
	usage
	exit -1
fi

IMAGE=$2
IMAGE=`echo $IMAGE | awk '{n=split($1,img,"/"); if(n==3)printf "%s/%s",img[2],img[3]; else printf "%s/%s",img[1],img[2]}'`

fulcon-list-running | awk 'BEGIN{r=1}{if($1=="'$NAME'")r=0}END{exit(r)}'
if [ $? -eq 0 ]; then
	echo "error: already started" $NAME 
	exit -1
fi

fulcon-list-all | awk 'BEGIN{r=1}{if($1=="'$NAME'")r=0}END{exit(r)}'
if [ $? -eq 0 ]; then
	echo "error: already existed" $NAME 
	exit -1
fi

fulcon-sysgen $NAME $IMAGE

exit 0


