#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: lib-start NAME"
}

if [ $# -eq 1 ]; then
	NAME=$1
else
	usage
	exit -1
fi

fulcon-list-running | awk 'BEGIN{r=1}{if ($1=="'$NAME'")r=0}END{exit(r);}'
if [ $? -eq 0 ]; then
	echo "error: already started" $NAME 
	exit -1
fi

fulcon-list-all | awk 'BEGIN{r=1}{if ($1=="'$NAME'")r=0}END{exit(r);}'
if [ $? -ne 0 ]; then
	echo "error: can't find" $NAME
	exit -1
fi

echo -n "started " 

CPUSET=`cat $LIBDIR/container/$NAME/resource/cpuset`
CPU=`cat $LIBDIR/container/$NAME/resource/cpu | \
	awk '{printf "%3.2f",$1/1000}'`
MEM=`cat $LIBDIR/container/$NAME/resource/mem`

(sleep 1; fulcon resource -c $CPU -n $CPUSET -m $MEM $NAME >& /dev/null ) &
fulcon-start $NAME 

exit 0


