#!/bin/bash 

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDIR=/var/lib/fulcon

usage()
{
	echo "usage: lib-list [ NAME ]"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

ALLCONT=`fulcon-list-all | awk '{printf "%s ",$1}'`

list1()
{
	NAME=$1
	# mkdir -p $FULCONDIR/slot/$NAME/net
	# mkdir -p $FULCONDIR/container/$NAME/net
	if [ -f /var/lib/fulcon/container/$NAME/imagename ]; then
		IMAGE=`cat /var/lib/fulcon/container/$NAME/imagename`
		IPADDR=""
		STATUS=`fulcon-status $NAME`
		if [ x"$STATUS" == x"RUNNING" ]; then
			# network information
			IPADDR="`fulcon-ip $NAME` "
		fi

		# autostart information
		if [ -f $SLOTOSDIR/slot/$i/autostart ]; then
			AUTOSTART="A"
		else
			AUTOSTART="-"
		fi

		# network information
		for k in `lsdir $FULCONDIR/container/$NAME/net`
		do
			IP1=`awk '{printf "%s ",$3}' $FULCONDIR/container/$NAME/net/$k`
			IPADDR="$IPADDR$IP1"
		done

		printf "%s\t%s\t%s %s %s %s %s $IPADDR\n" \
			$NAME $STATUS \
			`cat $FULCONDIR/container/$NAME/resource/cpu | awk '{printf "%3d",int($1/1000)}'` \
			`cat $FULCONDIR/container/$NAME/resource/cpuset` \
			`cat $FULCONDIR/container/$NAME/resource/mem | awk '{printf "%dm",int($1/1024/1024)}'` \
			$AUTOSTART $IMAGE
	fi
}

if [ $# -eq 1 ]; then
	list1 $1
else
	for i in $ALLCONT
	do
		list1 $i
	done | sort
fi

exit 0


