#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

NUMOFARGS=$#

usage()
{
	echo "usage: list"
}

if [ $NUMOFARGS -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"list" ]; then
	list
else
	usage
	exit -1
fi

exit 0


