#!/bin/bash


# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: net-info NAME"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

CNAME=$1

if [ x"$CNAME" == x"net-info" ]; then
	ls $FULCONDIR/container/*/net/* >& /dev/null
	if [ $? -eq 0 ]; then
		cd  $FULCONDIR/container
		for i in `fulcon list | awk '{printf "%s\n",$1}'`
		do
			echo $i
			N=`ls -1 $i/net | wc -l `
			if [ $N -ne 0 ]; then
				cat $i/net/* | awk '{printf "\t%s\n",$0}'
			fi
			echo
		done
	fi
	exit 0
fi

ls  $FULCONDIR/container/$CNAME/net/* >& /dev/null
if [ $? -eq 0 ]; then
	cat $FULCONDIR/container/$CNAME/net/*
fi

exit 0
