#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage() {
	echo "usage: set-passwd NAME USER"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"set-passwd" ]; then
	usage
	exit -1
fi

. set-passwd $@

exit 0


