#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

# check options
OPT_FLG=""
FLG_N=0
RNUM=0

while getopts n: OPT
do
  case $OPT in
    "n" ) FLG_N=1 ; RNUM=$OPTARG ;;
  esac
done

shift `expr $OPTIND - 1`

usage()
{
	echo "usage: start NAME NAME ..."
	echo "       start [-n REPEAT_NUMBER] NAME  ..."
}


if [ $FLG_N -eq 1 ]; then
	if [ $# -ne 1 ]; then
		usage
		exit -1
	fi
	NAME=$1
	if [ $RNUM -gt 0 -a $RNUM -lt 1000 ]; then
		for i in `seq $RNUM`
		do
			N=`printf "%04d" $i`
			start $OPT_FLG $NAME$N

			NETDIR=$FULCONDIR/container/$NAME$N/net
			ls $NETDIR/* >& /dev/null
			if [ $? -eq 0 ]; then
				for j in `ls -1 $NETDIR`
				do
					sh $NETDIR/$j
				done
			fi
		done;
		exit 0
	else
		echo "REPEAT_NUMBER must be [1...999]"
		exit -1
	fi

fi

if [ $# -ge 1 ]; then
	NAMES=$@
else
	usage
	exit -1
fi

if [ x"$NAMES" == x"start" ]; then
	usage
	exit -1
fi

for i in $NAMES
do
	start $OPT_FLG $i

	NETDIR=$FULCONDIR/container/$i/net/
	ls $NETDIR/* >& /dev/null
	if [ $? -eq 0 ]; then
		for j in `ls -1 $NETDIR`
		do
			sh $NETDIR/$j
		done
	fi
done

exit 0


