#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage()
{
	echo "usage: suspend NAME"
}

if [ $# -eq 1 ]; then
	NAMES=$@
else
	usage
	exit -1
fi

. suspend $NAMES

exit 0

