#!/bin/sh

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`driver-name`
PATH=/usr/lib64/fulcon/driver/$FULCONDRIVER:$PATH

usage() {
	echo "usage: update"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"update" ]; then
	usage
	exit -1
fi

. update $@

exit 0
