#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki


# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

usage()
{
	echo "usage: add-user NAME USER [ PASSWORD ]" 
}

if [ $# -ne 2 -a $# -ne 3 ]; then
	usage
	exit -1
fi

ARGS=$#

LXCNAME=$1
USERNAME=$2

PASSWORD=""
if [ $ARGS -eq 3 ]; then
	PASSWORD=$3
fi

docker exec -it $LXCNAME useradd -m $USERNAME
if [ $? -ne 0 ]; then
	echo "error: add-user is failed"
	exit -1
fi

docker exec -it $LXCNAME mkdir -p /etc/sudoers.d
SUDOERS_LINE="echo $USERNAME ALL\=\(ALL\) ALL  > /etc/sudoers.d/$USERNAME"
docker exec -it $LXCNAME /bin/sh -c "$SUDOERS_LINE"
docker exec -it $LXCNAME chmod 440 /etc/sudoers.d/$USERNAME

if [ $ARGS -eq 3 ]; then
	docker exec -it $LXCNAME /bin/sh -c "printf \"%s\n%s\n\" $PASSWORD $PASSWORD | passwd $USERNAME"
else
	docker exec -it $LXCNAME passwd $USERNAME
fi

exit 0
