#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: clone-newimage BASENAME NAME"
}

if [ $# -eq 2 ]; then
	BASENAME=$1
	NAME=$2
else
	usage
	exit -1
fi

IMAGE=`docker ps -a --no-trunc | awk '(NR>1){if($NF=="'$BASENAME'"){split($2,ar,":");\
	split(ar[1], ar2, "-"); printf "%s",ar2[1] }}'`

# create a new image
#docker export  $BASENAME | docker import - $IMAGE-$NAME
docker commit $BASENAME $IMAGE-$NAME  >& /dev/null

exit 0


