#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: clone CONTAINER_NAME NEW_IMAGENAME "
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

CONTAINER=$1
IMAGENAME=`basename $2`

docker commit $CONTAINER fulcon/$IMAGENAME

if [ $? -eq 0 ]; then
	echo "cloned new image:" fulcon/$IMAGENAME
else
	echo "error: clone is failed"
	exit -1
fi

docker rmi `docker images | egrep none | awk '{printf "%s ",$3}'` >& /dev/null


exit 0


