#!/bin/sh

# Copyright (C) 2015 NIWA Hideyuki

# check options
FLG_E=0

usage() {
	echo "usage: console NAME"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

NAME=$1

docker exec -it $NAME /bin/bash

exit 0
