#!/bin/sh

# Copyright (C) 2015 NIWA Hideyuki

# check options
FLG_E=0

while getopts e OPT
do
  case $OPT in
    "e" ) FLG_E=1 ;;
  esac
done

shift `expr $OPTIND - 1`

usage() {
	echo "usage: console [ -e ] NAME"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

NAME=$1

if [ $FLG_E -ne 0 ]; then
	docker exec -it $NAME /bin/bash
else
	echo Attached $NAME"."  
	echo To enter console, hit Enter.
	echo To exit  console, ^p^q is pushed. 

	docker attach $NAME
fi

exit 0
