#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki


CPUSETDIR="/sys/fs/cgroup/cpuset/system.slice/"

if [ $# -ne 2 -a $# -ne 1 ]; then
	echo "usage: cpuset CONTAINER_NAME [VALUE]"
	echo "error: VALUE must be 1 or [2-5] or [3,8]"
	exit 1
fi

if [ ! -d $CPUSETDIR ]; then
	echo "error:" $CPUSETDIR "is not exist"
	exit 1
fi

ARGN=$#

NAME=$1
if [ $ARGN -eq 2 ]; then
	VAL=$2
fi

DID=`docker-find-id $NAME`
if [ $? -ne 0 ]; then
	echo "error: can't find a container"
	exit -1
fi

cd $CPUSETDIR
ls docker-${DID}*  >& /dev/null
if [ $? -ne 0 ]; then
	exit 0
fi

for i in docker-${DID}*
do
	if [ $ARGN -eq 2 ]; then
		echo $VAL > $i/cpuset.cpus
	else
		cat $i/cpuset.cpus | awk '{printf "CPUSET : %s\n",$1}'
	fi
done 
exit 0

