#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: deploy CONTAINER_NAME SRC_FILE DEST_PATH"
}

if [ $# -ne 3 ]; then
	usage
	exit -1
fi

NAME=$1
SRC_FILE=$2
DEST_PATH=$3

docker cp $SRC_FILE $NAME:$DEST_PATH





