#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: deploy CONTAINER_NAME SRC_FILE DEST_PATH"
}

if [ $# -ne 3 ]; then
	usage
	exit -1
fi

NAME=$1
SRC_FILE=$2
DEST_PATH=$3

VERCHK=`docker images | awk '{split($3,a,".");if(a[1]>=1&&a[2]>=8)print "t"; else print "f"}'`
if [ x"$VERCHK" == x"f" ]; then
	echo "error: it is a older than version 1.8"
	exit -1
fi

docker cp $SRC_FILE $NAME:$DEST_PATH

if [ $? -eq 0 ]; then
	echo "deployed file :  $NAME ${DEST_PATH}/${SRC_FILE}"
fi



