#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: erase [ -f ] NAME"
}

# check options
OPT_FLG=""
FLG_F=0

while getopts f OPT
do
  case $OPT in
    "f" ) FLG_F=1; OPT_FLG=" " ;;
    \?  ) usage; exit -1;;
  esac
done

shift `expr $OPTIND - 1`

if [ $# -eq 1 ]; then
	NAME=$1
else
	usage
	exit -1
fi

docker ps -a | awk '(NR>1){ printf "%s\n",$NF }' | egrep $NAME >& /dev/null
if [ $? -ne 0 ]; then
	echo "error: can't find" $NAME
	exit -1
fi

docker stop $NAME >& /dev/null
docker rm   $NAME >& /dev/null
echo "erased" $NAME

(docker rmi `docker images | grep '<none>' | awk '{print$3}'`) >& /dev/null

exit 0


