#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

OCFDIR=/var/lib/fulcon/OCF

IMAGENAME=$1

REPO=`docker images --no-trunc docker.io/fulcon/$IMAGENAME | awk 'NR>1{print $1}'`
if [ x"$REPO" != x"" ]; then
	REPO="docker.io/"
fi

if [ -f $OCFDIR/$IMAGENAME/$IMAGENAME.tgz ]; then
	echo "OCF image" $IMAGENAME "is loading"
	cat $OCFDIR/$IMAGENAME/$IMAGENAME.tgz | gzip -d -c | docker import - ${REPO}fulcon/$IMAGENAME
	if [ $? -eq 0 ]; then
		echo $IMAGENAME "is loaded"
		CONT=`docker images | egrep none | awk '{printf "%s ",$3}'`
		if [ x"$CONT" != x"" ]; then
		        docker rmi $CONT >& /dev/null
		fi
		echo $IMAGENAME "is converted docker image:" fulcon/$IMAGENAME
		exit 0
	else
		echo "error:" $IMAGENAME "is not conveted docker image"
		exit -1
	fi
fi


