#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

SRC_FILE=$1
NAME=$2
DEST_PATH=$3

VERCHK=`docker -v | awk '{split($3,a,".");if(a[1]>=1&&a[2]>=8)print "t"; else print "f"}'`
if [ x"$VERCHK" == x"f" ]; then
	echo "error: can't copy file, because docker version is a older than version 1.8"
	exit -1
fi

docker cp $SRC_FILE $NAME:$DEST_PATH


