#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

docker inspect $1 | \
  awk 'BEGIN{f=0} \
       {if(($1=="\"Running\":")&&($2=="true,")){f=1; \
        }else if(($1=="\"Paused\":")&&($2=="true,")){f=2;exit(0);}} \
       END{if(f==0)print"STOPPED"; \
           else if(f==2)print"PAUSED"; \
           else print"RUNNING"; }'

