#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

ls /var/lib/fulcon/driver/dockerfile/* >& /dev/null
if [ $? -ne 0 ]; then 
	echo "there is not a image"
	exit -1
fi

usage() {
	echo "usage: image-catalog"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"image-catalog" ]; then
	usage
	exit -1
fi

cd /var/lib/fulcon/driver/dockerfile

for i in *
do
	echo "fulcon/"$i
done

exit 0

