#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: list "
}

RUNNING=`docker ps --no-trunc    | awk 'NR>1{printf "%s;%s\n",$NF,$2}'`
ALLCONT=`docker ps --no-trunc -a | awk 'NR>1{printf "%s;%s\n",$NF,$2}'`
for i in $ALLCONT
do
	NAME=`echo $i | awk -F ";" '{print $1}'`
	IMAGE=`echo $i | awk -F ";" '{print $2}'`
	echo $RUNNING | egrep -w $i >& /dev/null
	if [ $? -eq 0 ]; then
		printf "%s\t\tRUNNING\t\t%s\n" $NAME $IMAGE
	else
		printf "%s\t\tSTOPPED\t\t%s\n" $NAME $IMAGE
	fi
done | sort

exit 0


