#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

OCFDIR=/var/lib/fulcon/OCF

usage()
{
	echo "usage: load-ocf IMAGENAME"
}

if [ $# -ne 1 ]; then
echo debug $#
	usage
	exit -1
fi

if [ x"$1" == x"load-ocf" ]; then
	usage
	exit -1
fi

IMAGENAME=`basename $1`

if [ -f $OCFDIR/$IMAGENAME/$IMAGENAME.tgz ]; then
	echo "OCF image" $IMAGENAME "is loading"
	cat $OCFDIR/$IMAGENAME/$IMAGENAME.tgz | docker import - fulcon/$IMAGENAME
	if [ $? -eq 0 ]; then
		echo $IMAGENAME "is loaded"
		CONT=`docker images | egrep none | awk '{printf "%s ",$3}'`
		if [ x"$CONT" != x"" ]; then
		        docker rmi $CONT
		fi
		echo $IMAGENAME "is converted docker image:" fulcon/$IMAGENAME
		exit 0
	else
		echo "error:" $IMAGENAME "is not conveted docker image"
		exit -1
	fi
fi

exit 0
