#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: ls-image"
}

if [ $# -ne 1 -o x"$1" != x"ls-image" ]; then
	usage
	exit -1
fi

echo "fulcon images:"
IMAGES=`docker images --no-trunc | awk '($1~/fulcon\//){printf "\t%s\n",$1}'`

if [ x"$IMAGES" == x"" ]; then
	exit -1
else
	echo $IMAGES
	exit 0
fi
