#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki


# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

if [ $# -ne 2 ]; then
	echo "usage: net-route-del CONTAINER_NAME NET_ADDR "
	exit -1
fi

LXCNAME=$1
NET_ADDR=$2

brctl show  |& egrep ${LXCNAME} >& /dev/null
if [ $? -ne 0 ]; then
	echo "error: can't find" ${LXCNAME}
	exit -1
fi

LXCPROC=`docker-find ${LXCNAME}`
if [ $? -ne 0 ]; then
	echo "error: can't find" ${LXCNAME}
	exit -1
fi

mkdir -p /var/run/netns/
ln -s /proc/${LXCPROC}/ns/net /var/run/netns/${LXCNAME}

# delete a routing table
ip netns exec ${LXCNAME} ip route del $NET_ADDR 

rm -f /var/run/netns/${LXCNAME}

exit 0
