#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki


# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

# check options
FLG_N=0 ; NUM=""
FLG_D=0 ; DEV=""

while getopts n:d: OPT ; do
  case $OPT in
  n) FLG_N=1 ; NUM=$OPTARG ;;
  d) FLG_D=1 ; DEV=$OPTARG ;;
  esac
done
shift $((OPTIND - 1))

usage()
{
	echo "usage: net-del [ -n NUMBER ] CONTAINER_NAME"
	echo "usage: net-del [ -d DEVICE ] "
}

# check args
if [ $FLG_D -eq 1 -a $# -ne 0 ]; then
	usage
	exit -1
fi
if [ $FLG_D -ne 1 -a $# -ne 1 ]; then
	usage
	exit -1

fi

if [ $FLG_D -eq 1 -a $FLG_N -eq 1 ]; then
	usage
	exit -1
fi


if [ $FLG_D -eq 1 ]; then
	ip link delete $DEV type veth 
	echo "deleted" $DEV
else
	LXCNAME=$1
	brctl show  |& egrep ${LXCNAME}${NUM} >& /dev/null
	if [ $? -ne 0 ]; then
		echo "error: can't find" vh${LXCNAME}${NUM}
		exit -1
	fi
	ip link delete ${LXCNAME}${NUM} type veth 
	echo "deleted" ${LXCNAME}${NUM}
fi

exit 0
