#!/bin/bash


# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: net-br-info"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ $# -eq 1 -a x"$1" != x"net-br-info" ]; then
	usage
	exit -1
fi

for i in `brctl show | egrep fulcon | awk '{print $1}' `
do
	N=`brctl show $i | awk '($1=="'$i'"){print NF}'`
	if [ $N -eq 4 ]; then
		ip a show $i
		echo
		brctl show $i
		echo
	else
		ip link set $i down
		brctl delbr $i
	fi
done

exit 0
