#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki


# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

# check args
if [ $# -ne 2 ]; then
	echo "usage: net-gateway CONTAINER_NAME IP_ADDR"
	exit -1
fi

LXCNAME=$1
LXCGATEWAY=$2

brctl show  |& egrep ${LXCNAME} >& /dev/null
if [ $? -ne 0 ]; then
	echo "error: can't find" ${LXCNAME}
	exit -1
fi

LXCPROC=`docker-find ${LXCNAME}`
if [ $? -ne 0 ]; then
	echo "error: can't find" ${LXCNAME}
	exit -1
fi

mkdir -p /var/run/netns/
ln -s /proc/${LXCPROC}/ns/net /var/run/netns/${LXCNAME}

# setting up of gateway
if [ x$LXCGATEWAY != x"" ]; then
	ip netns exec ${LXCNAME} ip route del default
	IPADDR=$LXCGATEWAY
	ip netns exec ${LXCNAME} ip route add default via ${IPADDR}
fi

rm -f /var/run/netns/${LXCNAME}

exit 0
