#!/usr/bin/python

# Copyright (C) 2015 NIWA Hideyuki

# -*- coding: utf-8 -*-

import sys
from optparse import OptionParser

parser = OptionParser()

(options, args) = parser.parse_args(sys.argv)

argc = len(args)

if (argc != 2):
    print "usage : parmchk-num-kmg val"
    quit()

parm = args[1]

l = len(parm)
c = parm[l-1]

if (((c == 'k') or (c == 'm') or (c == 'g') or (c == 't') or (c == 'K') or
     (c == 'M') or (c == 'G') or (c == 'T'))):
    p = parm[0:l-1]
else:
    p = parm

if p.isdigit():
    exit(0)
else:
    exit(1)
