#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

DOCKERFILEDIR=/var/lib/fulcon/driver/dockerfile

ls $DOCKERFILEDIR/*
if [ $? -ne 0 ]; then
	echo "Dockerfile is not exist"
	exit 0
fi

cd $DOCKERFILEDIR
for i in *
do
	cd $i
	echo docker build -t fulcon/$i .
	docker build --no-cache -t fulcon/$i .
	echo 
	echo
	cd ..
done

(docker rmi `docker images | grep '<none>' | awk '{print$3}'`) >& /dev/null
echo 

exit 0

