#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

# check options
OPT_FLG=""
FLG_I=0

while getopts i OPT
do
  case $OPT in
    "i" ) FLG_I=1; OPT_FLG="-i " ;;
  esac
done

shift `expr $OPTIND - 1`

usage()
{
	echo "usage: start [ -i ] NAME"
}

if [ $# -eq 1 ]; then
	NAME=$1
else
	usage
	sleep 5
	exit -1
fi

docker ps | awk '(NR>1){ printf "%s\n",$NF }' | egrep $NAME >& /dev/null
if [ $? -eq 0 ]; then
	echo "error: already started" $NAME 
	sleep 5
	exit -1
fi

docker ps -a | awk '(NR>1){ printf "%s\n",$NF }' | egrep $NAME >& /dev/null
if [ $? -ne 0 ]; then
	echo "error: can't find" $NAME
	sleep 5
	exit -1
fi

echo -n "started " 

CPUSET=`cat $LIBDIR/container/$NAME/resource/cpuset`
CPU=`cat $LIBDIR/container/$NAME/resource/cpu | \
	awk '{printf "%3.2f",$1/1000}'`
MEM=`cat $LIBDIR/container/$NAME/resource/mem`

(sleep 1; fulcon resource -c $CPU -n $CPUSET -m $MEM $NAME >& /dev/null ) &
docker start $OPT_FLG $NAME 

exit 0


