#!/bin/bash 

# Copyright (C) 2015 NIWA Hideyuki

LIBDIR="/var/lib/fulcon/"

usage()
{
	echo "usage: sysgen NAME IMAGE"
}

if [ $# -eq 2 ]; then
	NAME=$1
else
	usage
	exit -1
fi

IMAGE=$2

docker ps | awk '(NR>1){ if ($NF == "'$NAME'"){exit -1} }'
if [ $? -ne 0 ]; then
	echo "error: already started" $NAME 
	exit -1
fi

docker ps -a | awk '(NR>1){ if ($NF == "'$NAME'"){exit -1} }'
if [ $? -ne 0 ]; then
	echo "error: already existed" $NAME 
	exit -1
fi

CPUSET=`cat /sys/fs/cgroup/cpuset/cpuset.cpus`
OPTCPUSET=`docker run --help | egrep '\-\-cpuset' | egrep -v mem | awk '{print $1}' | awk -F '=' '{print $1}'`

start_docker() {
	docker run -d ${OPTCPUSET}=${CPUSET} -c 100 -m 512m \
	--name $NAME --hostname $NAME \
	-v /sys/fs/cgroup:/sys/fs/cgroup:ro \
        --cap-add=ALL \
	--privileged \
	$IMAGE /sbin/init 
	mkdir -p $LIBDIR/container/$NAME/resource
	echo $IMAGE >  $LIBDIR/container/$NAME/imagename
	echo $CPUSET > $LIBDIR/container/$NAME/resource/cpuset
	echo "100000" > $LIBDIR/container/$NAME/resource/cpu
	echo "512m" > $LIBDIR/container/$NAME/resource/mem
}

MSG=`start_docker < /dev/tty 2>&1 ` & 
if [ $? -eq 0 ]; then
	stty sane;
	echo "sysgened:" $NAME;
else
	stty sane;
	echo "error: can't sysgened" $NAME
	echo $MSG
fi

exit 0


