#!/bin/bash 

# Fulcon/slot-os Virtual-Platform
# Copyright (C) 2016 NIWA Hideyuki

umask 022

LOGFILE=/var/log/fulcon/slot-os.log

print_log1()
{
	EXLINE=$*
	DATETIME=`date "+%m%d:%H%M%S"`
	echo $DATETIME ":" slot-os $EXLINE >> $LOGFILE
}

print_log2()
{
	EXLINE=$*
	while read l
	do
		echo $l 1>&2
		echo $l | egrep "^error:" >& /dev/null
		if [ $? -eq 0 ]; then
			DATETIME=`date "+%m%d:%H%M%S"`
			echo $DATETIME ":" slot-os $EXLINE ":" $l >> $LOGFILE
		fi
	done

}

# check root
if [ ${EUID:-$UID} -ne 0 ] ; then
  echo "error: not executing without superuser privileges."
  exit 1
fi

export PATH=/usr/lib/slot-os/sbin:/usr/lib/fulcon/sbin:$PATH
export FULCONDIR=/var/lib/fulcon
export SLOTOSDIR=/var/lib/slot-os

mkdir -p /var/lib/slot-os

mkdir -p `dirname $LOGFILE`
touch $LOGFILE

if [ x"`fulcon ls-image | awk '$1=="fulcon/slot-os"{print $1}'`" != x"fulcon/slot-os" ]; then
  slot-os make-base-image
fi

FLG_H=0

while getopts h OPT
do
  case $OPT in
    "h" ) FLG_H=1 ;;
  esac
done
shift `expr $OPTIND - 1`

if [ $# -eq 0 ] ; then
	less /usr/lib/slot-os/doc/help.txt
else
  if [ -f /usr/lib/slot-os/sbin/$1 ]; then
    EXLINE=`echo /usr/lib/slot-os/sbin/$* | sed -e 's/\$//g' -e 's/\`//g' -e "s/'//g" -e 's/\"//g' -e 's/;//g' -e 's/&//g' -e 's/|//g'`
    case $1 in
    "make-base-image" ) print_log1 $* ;;
    "start" ) print_log1 $* ;;
    "stop"  ) print_log1 $* ;;
    "restart" ) print_log1 $* ;;
    "suspend" ) print_log1 $* ;;
    "resume" ) print_log1 $* ;;
    "backup" ) print_log1 $* ;;
    "backup-del" ) print_log1 $* ;;
    "backup-restore" ) print_log1 $* ;;
    "update" ) print_log1 $* ;;
    "update-prog" ) print_log1 $* ;;
    "update-deploy" ) print_log1 $* ;;
    esac

    case $1 in
    "make-base-image" ) . $EXLINE ;;
    "console" ) . $EXLINE ;;
    "list" ) . $EXLINE ;;
    "autostart" ) . $EXLINE ;;
    "help" ) . $EXLINE ;;
    "list" ) . $EXLINE ;;
    "backup-list" ) . $EXLINE ;;
    "br-info" ) . $EXLINE ;;
    "net-info" ) . $EXLINE ;;
    * ) . $EXLINE | print_log2 $* ;;
    esac

  else
    echo "error: unknown command:" $1
  fi
fi

exit 0
