#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: deploy COMMAND"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

if [ $# -lt 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"deploy" ]; then
	usage
	exit -1
fi

fulcon deploy $*


