#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: list [ SLOT_NUMBER ]"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}


list1()
{
	i=$1
	CNAME=`cat $SLOTOSDIR/slot/$i/fulcon`
	STATUS=""
	for j in `fulcon list | awk '{printf "%s:%s:%s\n",$1,$2,$3}'`
	do 
		STATUS=$STATUS`echo $j | awk -F :  '{if($1=="'$CNAME'")printf "%s",$2}'`
	done
	if [ x"$STATUS" == x"" ]; then
		STATUS="NONE"
		IPADDR=""
		cat /dev/null > $SLOTOSDIR/slot/$i/fulcon
		CNAME='-'
	else
		if [ x"$STATUS" == x"RUNNING" ]; then
			IPADDR=`fulcon net-info $CNAME | \
			awk '$1=="inet" && $2!="127.0.0.1/8"{printf "%s ", $2}'`
		else
			IPADDR=""
		fi
	fi

	printf "%2d :%8s %10s %3s %% %5s %7s " \
		$i $STATUS $CNAME \
		`cat $SLOTOSDIR/slot/$i/cpu` \
		`cat $SLOTOSDIR/slot/$i/cpuset` \
		`cat $SLOTOSDIR/slot/$i/memory`
	echo $IPADDR
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"list" ]; then
	NUM=$1
	NUM=`echo $NUM | sed -e 's/slot//'` 
	NUM=`expr $NUM + 0`

	if [ -d $SLOTOSDIR/slot/$NUM ]; then
		list1 $NUM
		exit 0
	else
		printf "error: slot%02d is not exist\n" $NUM
		exit -1
	fi
fi


if [ ! -x $SLOTOSDIR/slot -o ! -x $SLOTOSDIR/slot/0 ]; then
	echo "error: slot is not set."
	exit -1
fi

for i in `lsdir $SLOTOSDIR/slot | sort`
do
	list1 $i
done

exit 0
