#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: list [ SLOT_NUMBER ]"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

list1()
{
	i=$1
	CNAME=`cat $SLOTOSDIR/slot/$i/fulcon`
	LIST=`fulcon list $CNAME`
	STATUS=`echo $LIST | awk '{print $2}'`
	IMAGE=`echo $LIST | awk '{print $3}' | awk -F / '{print $2}'`
	if [ x"$STATUS" == x"" ]; then
		STATUS="NONE"
		IPADDR=""
		cat /dev/null > $SLOTOSDIR/slot/$i/fulcon
		CNAME='-'
	else
		IPADDR=`echo $LIST | cut -d ' ' -f 4-`
	fi

	if [ -d $SLOTOSDIR/slot/$i ]; then
		printf "%2d : %8s %s %3s %% %3s %s %s " \
			$i $STATUS $CNAME \
			`cat $SLOTOSDIR/slot/$i/cpu` \
			`cat $SLOTOSDIR/slot/$i/cpuset` \
			`cat $SLOTOSDIR/slot/$i/memory` \
			$IMAGE
	fi

	echo $IPADDR
}


if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"list" ]; then
	NUM=$1
	NUM=`echo $NUM | sed -e 's/slot//'` 
	NUM=`expr $NUM + 0`

	if [ -d $SLOTOSDIR/slot/$NUM ]; then
		list1 $NUM
		exit 0
	else
		printf "error: slot%02d is not exist\n" $NUM
		exit -1
	fi
fi


if [ ! -x $SLOTOSDIR/slot -o ! -x $SLOTOSDIR/slot/0 ]; then
	echo "error: there is no slot."
	exit -1
fi

if [ x"$1" == x"list" ]; then
	for i in `lsdir $SLOTOSDIR/slot | sort`
	do
		list1 $i
	done
else
		list1 $1
fi

exit 0
