#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: make-base-image"
}

if [ $# -eq 1 -a x"$1" == x"make-build-image" ]; then
	usage
	exit -1
fi

fulcon setup2

exit 0
