#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH
SLOTOSDIR=/var/lib/slot-os

umask 022

# function usage
usage()
{
	echo "usage: net-info"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

# check args
if [ $# -ne 1 ]; then
	usage
	exit -1
fi

fulcon net-info | egrep '^slot'

exit 0
