#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH
SLOTOSDIR=/var/lib/slot-os

umask 022

# function usage
usage()
{
	echo "usage: net-info"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

# check args
if [ $# -ne 1 ]; then
	usage
	exit -1
fi

net-slot-info()
{
	for i in `lsdir $SLOTOSDIR/slot`
	do
		SLOT=$i
		NAME=`cat $SLOTOSDIR/slot/$SLOT/fulcon`
		STAT=`fulcon list $NAME | awk '{print $2}'`
		if [ x"$STAT" != x"RUNNING" ]; then
			continue
		fi
		if [ x"$NAME" != x"" ]; then
			fulcon net-info $NAME | egrep eth0 | egrep inet | \
			  awk '{printf "slot%02d eth0\t\t%s\n",'$SLOT',$2}'
		fi
		if [ -d $SLOTOSDIR/slot/$SLOT/net ]; then
			for j in `lsdir $SLOTOSDIR/slot/$SLOT/net`
			do
				cat $SLOTOSDIR/slot/$SLOT/net/$j | \
				  awk '{printf "slot%02d vg%s_%s\t%s\n","'$SLOT'","'$NAME'",$4,$3}'
			done
		fi
	done
}


net-slot-info | sort

exit 0
