#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

FULCONDIR=/var/lib/fulcon
SLOTOSDIR=/var/lib/slot-os


usage()
{
	echo "usage: net-del SLOT_NUMBER NIC_NUMBER"
}

# check args
if [ $# -ne 2 ]; then
	usage
	exit -1
fi

SLOTNO=$1
NICNUM=$2
NAME=`cat $SLOTOSDIR/slot/$SLOTNO/fulcon`

if [ x"`fulcon list $NAME | awk '{print $2}'`" != x"STOPPED" ]; then
	fulcon net-del $NAME $NICNUM
fi

if [ $? -eq 0 ]; then
	rm -f  $SLOTOSDIR/slot/$SLOTNO/net/${NAME}_${NICNUM}
	rm -f  $FULCONDIR/container/$NAME/net/${NAME}_${NICNUM}
fi

exit 0

