#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

FULCONDIR=/var/lib/fulcon
SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: restore SLOT_NUMBER BACKUP_IMAGE"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}


if [ $# -ne 2 ]; then
	usage
	exit -1
fi

NUM=$1
IMAGE=$2

slot-os backup-list | awk 'BEGIN{r=1}{if($1=="'$IMAGE'")r=0}END{exit(r)}'
if [ $? -ne 0 ]; then
	echo "error: $IMAGE is not exist in backup-list"
	exit -1
fi

echo $IMAGE | egrep ^fulcon/ >& /dev/null
if [ $? -eq 1 ]; then
	IMAGE="fulcon/$IMAGE"
fi

NUM=`echo $NUM | sed -e 's/slot//'` 
NUM=`expr $NUM + 0`

SLOTNUM=`printf "slot%02d" $NUM`

NAME=`cat $SLOTOSDIR/slot/$NUM/fulcon`

fulcon erase $NAME
slot-sysgen $NUM $IMAGE

NAME=`cat $SLOTOSDIR/slot/$NUM/fulcon`

if [ -d $SLOTOSDIR/slot/$NUM/net ]; then
	cp -pr $SLOTOSDIR/slot/$NUM/net $FULCONDIR/container/$NAME/
fi

if [ -f $SLOTOSDIR/slot/$NUM/autostart ]; then
	fulcon autostart on  $NAME
else
	fulcon autostart off $NAME
fi

exit 0


