#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: sysgen NUMBER NAME"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}


if [ $# -ne 2 ]; then
	usage
	exit -1
fi

NUM=$1
NAME=$2

if [ ! -x $SLOTOSDIR/slot/$NUM ]; then
	printf "error: slot%02s is not exist" $NUM
	exit -1
fi

fulcon sysgen -c fulcon/slot-os $NAME
if [ $? -ne 0 ] ; then
	echo "error: $NAME is not able to start"
	exit -1
fi

if [ -f $SLOTOSDIR/slot/$NUM/lastname ]; then
	OLDNAME=`cat $SLOTOSDIR/slot/$NUM/lastname`
else
	OLDNAME=$NAME
fi
echo $NAME > $SLOTOSDIR/slot/$NUM/fulcon
echo $NAME > $SLOTOSDIR/slot/$NUM/lastname

fulcon resource  \
	-c `cat $SLOTOSDIR/slot/$NUM/cpu` \
	-n `cat $SLOTOSDIR/slot/$NUM/cpuset` \
	-m `cat $SLOTOSDIR/slot/$NUM/memory` \
	$NAME

OLDPATH=$PATH
PATH=/usr/lib/fulcon/sbin:$PATH
if [ -d $SLOTOSDIR/slot/$NUM/net ]; then
	for i in `lsdir $SLOTOSDIR/slot/$NUM/net`
	do
		NEWFILE=`echo $i | sed -e "s/$OLDNAME/$NAME/"`
		sed -i -e "s/ $OLDNAME / $NAME /" $SLOTOSDIR/slot/$NUM/net/$i
		mv $SLOTOSDIR/slot/$NUM/net/$i $SLOTOSDIR/slot/$NUM/net/$NEWFILE >& /dev/null
		bash $SLOTOSDIR/slot/$NUM/net/$NEWFILE
	done
fi
PATH=$OLDPATH

