#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/slot-os/lib:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

SLOTOSDIR=/var/lib/slot-os

usage()
{
	echo "usage: update ( all | NUMBER ...) "
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}


if [ $# -lt 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"update" ]; then
	usage
	exit -1
fi

if [ x"$1" == x"all" ]; then
	for i in `slot-os list | awk '{print $4}'`
	do
		fulcon update $i
	done
else
	for i in `slot-os list $* | awk '{print $4}'`
	do
		fulcon update $i
	done
fi

