#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

br-brif-list | awk '{ \
	for(i=2;i<=NF;i++){ \
		system("ovs-vsctl del-port "$1" "$i); \
	}}'

BR=`br-br-list`

if [ x"$BR" != x"" ]; then
	for i in $BR
	do
		ip link set $i down
		ovs-vsctl del-br $i >& /dev/null
	done
fi

exit 0
