#!/bin/bash

# Copyright (C) 2016 NIWA Hideyuki

brctl show | awk 'BEGIN{f=0} \
	NR>1{ \
	if(NF==4){if(f!=0){printf "\n"}f=1;printf "%s %s ",$1,$4} \
	else if(NF==3){if(f!=0){printf "\n"}f=1;printf "%s\n",$1} \
	else {printf "%s ",$1}
	}' | egrep "^fulcon" 
