#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: br-del BRIDGE_NUMBER"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"br-del" ]; then
	usage
	exit -1
fi

BRNO=$1
echo $BRNO | egrep fulcon >& /dev/null
if [ $? -ne 0 ]; then
	BRNO=fulcon$BRNO
fi

# delete all interface
for i in `brctl show $BRNO | awk 'NR>1{print $NF}'`
do
	brctl delif $BRNO $i
done

# delete bridge
ip link set $BRNO down
brctl delbr $BRNO


