#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
BRIDGEDRIVER=`fulcon bridge-name`
PATH=/usr/lib/fulcon/driver/$BRIDGEDRIVER:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: br-del BRIDGE_NUMBER"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"br-del" ]; then
	usage
	exit -1
fi

BRNO=$1
echo $BRNO | egrep fulcon >& /dev/null
if [ $? -ne 0 ]; then
	BRNO=fulcon$BRNO
fi

# delete all interface
BRIFLIST=`br-if-list $BRNO`
if [ x"$BRIFLIST" != x"" ]; then
	for i in $BRIFLIST
	do
		br-delif $BRNO $i
	done
fi

# delete bridge
ip link set $BRNO down
br-delbr $BRNO


