#!/bin/bash

FULCONDRIVER=`fulcon driver-name`
BRIDGEDRIVER=`fulcon bridge-name`
PATH=/usr/lib/fulcon/driver/$BRIDGEDRIVER:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: br-info"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ $# -eq 1 -a x"$1" != x"br-info" ]; then
	usage
	exit -1
fi

for i in `br-show | egrep fulcon | awk '{print $1}' `
do
	N=`br-show $i | awk '($1=="'$i'"){print NF}'`
	if [ $N -eq 4 ]; then
		ip a show $i
		echo
		br-show $i
		echo
	else
		ip link set $i down
		br-delbr $i
	fi
done

exit 0
