#!/bin/bash

FULCONDRIVER=`fulcon driver-name`
BRIDGEDRIVER=`fulcon bridge-name`
PATH=/usr/lib/fulcon/driver/$BRIDGEDRIVER:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

# Copyright (C) 2015 NIWA Hideyuki

usage()
{
	echo "usage: br-info"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ $# -eq 1 -a x"$1" != x"br-info" ]; then
	usage
	exit -1
fi

br-brif-list

exit 0
