#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: clone CONTAINER_NAME NEW_IMAGENAME"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

. lib-clone $@

exit 0


