#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage() {
	echo "usage: del-user NAME USER"
}

if [ $# -ne 2 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"del-user" ]; then
	usage
	exit -1
fi

. lib-del-user $@

exit 0


