#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage()
{
	echo "usage: del-image IMAGE_NAME ..."
}

if [ $# -eq 0 ]; then
	usage
	exit -1
fi

if [ $# -eq 1 -a x"$1" == x"del-image" ]; then
	usage
	exit -1
fi

IMAGES=$@

for i in $IMAGES
do
	IMG=`basename $i`
	del-image fulcon/$IMG
done

exit 0

