#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

# check options
OPT_FLG=""
FLG_N=0
RNUM=0

usage()
{
	echo "usage: erase NAME  ..."
	echo "usage: erase [-n REPEAT_NUMBER] NAME"
}

while getopts n: OPT
do
  case $OPT in
    "n" ) FLG_N=1; RNUM=$OPTARG;;
    \?  ) usage; exit -1;;
  esac
done
shift `expr $OPTIND - 1`

if [ $FLG_N -eq 1 ]; then
	if [ $# -ne 1 ]; then
		usage
		exit -1
	fi
	NAME=$1
	if [ $RNUM -gt 0 -a $RNUM -lt 1000 ]; then
		for i in `seq $RNUM`
		do
			N=`printf "%04d" $i`
			lib-erase $NAME$N
			rm -rf $FULCONDIR/container/$NAME$N
		done;
		exit 0
	else
		echo "error: REPEAT_NUMBER must be [1...999]"
		exit -1
	fi

fi

if [ $# -ge 1 ]; then
	NAMES=$@
else
	usage
	exit -1
fi

if [ x"$NAMES" == x"erase" ]; then
	usage
	exit -1
fi

for i in $NAMES
do
	lib-erase $OPT_FLG$i
	rm -rf $FULCONDIR/container/$OPT_FLG$i
done

exit 0


