#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

NUMOFARGS=$#

usage()
{
	echo "usage: list { NAME }"
}

if [ $NUMOFARGS -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"list" ]; then
	lib-list
else
	lib-list | awk '{if($1=="'$1'")print}'
fi

exit 0


