#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: load-ocf IMAGENAME"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"load-ocf" ]; then
	lib-load-ocf $@
else
	usage
	exit -1
fi

exit 0


