#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: ls-image"
}

if [ $# -ne 1 -o x"$1" != x"ls-image" ]; then
	usage
	exit -1
fi

. lib-ls-image $@


