#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

usage()
{
	echo "usage: ls-image"
}

if [ $# -ne 1 -o x"$1" != x"ls-image" ]; then
	usage
	exit -1
fi

. ls-image $@


