#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

OCFDIR=/var/lib/fulcon/OCF

usage()
{
	echo "usage: ls-ocf"
}

if [ $# -ne 1 -a x"$1" != x"ls-ocf" ]; then
	usage
	exit -1
fi

mkdir -p $OCFDIR
cd $OCFDIR
echo "OCF images:"
OCFIMAGES=`ls -1 | awk '{printf "\t%s\n",$1}'`

if [ x"$OCFIMAGES" == x"" ]; then
	exit -1
else
	echo $OCFIMAGES
	exit 0
fi



