#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH
FULCONDIR=/var/lib/fulcon

usage()
{
	echo "usage: net-info NAME"
}

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

CNAME=$1

display_info()
{
	i=$1
	echo $i
	fulcon-exec $i ip a show
	echo
}

net-fulcon-info()
{
	for i in `lsdir $FULCONDIR/container`
	do
		NAME=$i
		STAT=`fulcon list $NAME | awk '{print $2}'`
		if [ x"$STAT" == x"RUNNING" ]; then
			if [ x"$NAME" != x"" ]; then
				display_info $NAME | egrep eth0 | egrep inet | \
				  awk '{printf "%s\teth0\t\t%s\n","'$NAME'",$2}'
			fi
		fi
		if [ -d $FULCONDIR/container/$NAME/net ]; then
			for j in `lsdir $FULCONDIR/container/$NAME/net`
			do
				cat $FULCONDIR/container/$NAME/net/$j | \
				  awk '{printf "%s\tvg%s_%s\t%s\n","'$NAME'","'$NAME'",$4,$3}'
			done
		fi
	done
}


net-fulcon-info | sort

exit 0
