#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:$PATH

FULCONDIR=/var/lib/fulcon

# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

usage()
{
	echo "usage: net-del -n NUMBER CONTAINER_NAME"
}

# check options
FLG_N=0 ; NUM=""

while getopts n: OPT ; do
  case $OPT in
  n) FLG_N=1 ; NUM=$OPTARG ;;
  \? ) usage; exit -1;;
  esac
done
shift $((OPTIND - 1))

# check args
if [ $# -ne 1 ]; then
	usage
	exit -1
fi

# check number
if [ $FLG_N -ne 1 ]; then
	usage
	echo 'error: It is necessary to specify "-n NUMBER"'
	exit -1
fi

LXCNAME=$1
brctl show  |& egrep ${LXCNAME}${NUM} >& /dev/null
if [ $? -ne 0 ]; then
	echo "error: can't find" ${LXCNAME}${NUM}
	exit -1
fi
ip link delete ${LXCNAME}${NUM} type veth 
echo "deleted" ${LXCNAME}${NUM}

# delete a IP address for container
rm -f $FULCONDIR/container/${LXCNAME}/net/${LXCNAME}${NUM}

# check bridges
for i in `brctl show | egrep fulcon | awk '(NF==3){print $1}'`
do
	ip link set $i down
	brctl delbr $i
done

exit 0
