#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

FULCONDIR=/var/lib/fulcon

# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

usage()
{
	echo "usage: net-del CONTAINER_NAME NIC_NUMBER "
}

# check args
if [ $# -ne 2 ]; then
	usage
	exit -1
fi

LXCNAME=$1
NUM=$2
brctl show  |& egrep ${LXCNAME}_${NUM} >& /dev/null
if [ $? -ne 0 ]; then
	echo "error: can't find" ${LXCNAME}_${NUM}
	exit -1
fi
ip link delete ${LXCNAME}_${NUM} type veth 
echo "deleted" ${LXCNAME}_${NUM}

# delete a IP address for container
rm -f $FULCONDIR/container/${LXCNAME}/net/${LXCNAME}_${NUM}

# check bridges
for i in `brctl show | egrep fulcon | awk '(NF==3){print $1}'`
do
	ip link set $i down
	brctl delbr $i
done

exit 0
