#!/bin/bash

# Copyright (C) 2015 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: net-info NAME"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

CNAME=$1

display_info()
{
	i=$1
	echo $i
	fulcon-exec $i ip a show
	echo
}

if [ x"$CNAME" == x"net-info" ]; then
	ls $FULCONDIR/container/* >& /dev/null
	if [ $? -eq 0 ]; then
		cd  $FULCONDIR/container
		for i in `fulcon list | awk '{printf "%s\n",$1}'`
		do
			STAT=`fulcon list $i | awk '{print $2}'`
			if [ x"$STAT" != x"RUNNING" ]; then
				continue
			fi
			display_info $i
		done
	fi
	exit 0
else
	STAT=`fulcon list $CNAME | awk '{print $2}'`
	if [ x"$STAT" == x"RUNNING" ]; then
		display_info $CNAME
	fi
fi

exit 0
