#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
BRIDGEDRIVER=`fulcon bridge-name`
PATH=/usr/lib/fulcon/driver/$BRIDGEDRIVER:/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

FULCONDIR=/var/lib/fulcon

# check root
if [ ${EUID:-${UID}} != 0 ]; then
    echo "error: Because you are not root, you cannot execute this command. "
    exit 1
fi

usage()
{
	echo "usage: net-del CONTAINER_NAME NIC_NUMBER "
}

# check args
if [ $# -ne 2 ]; then
	usage
	exit -1
fi

LXCNAME=$1
NUM=$2

network_delete()
{
	ip link delete ${LXCNAME}_${NUM} type veth >& /dev/null
	echo "deleted" ${LXCNAME}_${NUM}

	# delete a IP address for container
	rm -f $FULCONDIR/container/${LXCNAME}/net/${LXCNAME}_${NUM}

	# check bridges
	EMPTYLIST=`br-emptylist`
	if [ x"$EMPTYLIST" != x"" ]; then
		for i in $EMPTYLIST
		do
			ip link set $i down
			br-delbr $i
		done
	fi
}

br-check ${LXCNAME}_${NUM}
if [ $? -eq 0 ]; then
	network_delete
fi

if [ -d $FULCONDIR/container/$LXCNAME/net ]; then
	rm -f $FULCONDIR/container/$LXCNAME/net/${LXCNAME}_${NUM}
fi

exit 0
