#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: rename NAME NEW_NAME"
}

if [ $# -eq 2 ]; then
	NAMES=$@
else
	usage
	exit -1
fi

. lib-rename $NAMES

exit 0

