#!/bin/sh

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage() {
	echo "usage: resource [-c CPU] [-n CPUSET] [-m MEM] NAME "
}

# check options
FLG_C=0; CPU=""
FLG_N=0; CPUSET=""
FLG_M=0; MEM=""

while getopts c:m:n: OPT
do
  case $OPT in
    "c" ) FLG_C=1 ; CPU=$OPTARG ;;
    "m" ) FLG_M=1 ; MEM=$OPTARG ;;
    "n" ) FLG_N=1 ; CPUSET=$OPTARG ;;
    \?  ) usage; exit -1;;
  esac
done

shift `expr $OPTIND - 1`

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"resource" ]; then
	usage
	exit -1
fi

CNAME=$1

if [ $FLG_C -eq 1 ]; then
	fulcon-cpu $CNAME $CPU
fi

if [ $FLG_N -eq 1 ]; then
	fulcon-cpuset $CNAME $CPUSET
fi

if [ $FLG_M -eq 1 ]; then
	fulcon-mem $CNAME $MEM
fi

fulcon-cpu $CNAME
fulcon-cpuset $CNAME
fulcon-mem $CNAME

exit 0

