#!/bin/bash

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage()
{
	echo "usage: resume NAME"
}

if [ $# -eq 1 ]; then
	NAMES=$@
else
	usage
	exit -1
fi

. lib-resume $NAMES

exit 0

