#!/bin/sh

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH
FULCONDIR=/var/lib/fulcon

lsdir() {
  ls -f --ind=none $1 | sed '/^\.\{1,2\}$/d'
}

usage() {
	echo "usage: update NAME ... "
}

if [ $# -lt 1 ]; then
	usage
	exit -1
fi

if [ x"$1" == x"update" ]; then
	usage
	exit -1
fi

LISTNAME=$*

. lib-update $LISTNAME

exit 0
