#!/bin/sh

# Copyright (C) 2015-2016 NIWA Hideyuki

FULCONDRIVER=`fulcon driver-name`
PATH=/usr/lib/fulcon/driver/$FULCONDRIVER:/usr/lib/fulcon/lib:$PATH

usage() {
	echo "usage: update"
}

if [ $# -ne 1 ]; then
	usage
	exit -1
fi

if [ x"$1" != x"update" ]; then
	usage
	exit -1
fi

. lib-update $@

exit 0
